# Small additions to MPV's excellent default controls.

Ctrl+s        screenshot window
Ctrl+Shift+s  screenshot video
Alt+RIGHT     playlist-next force
Alt+LEFT      playlist-prev force
Ctrl+UP       add sub-delay 0.1
Ctrl+DOWN     add sub-delay -0.1
Alt+UP        add audio-delay 0.1
Alt+DOWN      add audio-delay -0.1
Ctrl+=        add video-zoom 0.1
Ctrl+-        add video-zoom -0.1
Ctrl+0        set video-zoom 0; set video-pan-x 0; set video-pan-y 0
