#!/usr/bin/env bash
# Record this machine's packages, services, system tuning, and KDE settings in
# machine/ so scripts/restore-machine.sh can reproduce them elsewhere.
# Output is sorted and stripped of volatile state, so re-running it after a
# system change produces a reviewable diff. Credentials, host identity, and
# hardware-bound boot files are never applied; see docs/MACHINE-SNAPSHOT.md.

set -Eeuo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
OUT=${BLADE_MACHINE_DIR:-$ROOT/machine}
HOST_HOME=$(realpath -e -- "$HOME")
HOST_USER=$(id -un)

usage() {
    cat <<'EOF'
Usage: ./scripts/capture-machine.sh

Snapshot the current machine into machine/. Review the result with git diff.
EOF
}

case ${1:-} in
    -h|--help) usage; exit 0 ;;
    '') ;;
    *) usage >&2; exit 2 ;;
esac

for command in pacman systemctl python3 sort comm; do
    command -v "$command" >/dev/null 2>&1 || {
        printf 'capture-machine: %s is required\n' "$command" >&2
        exit 1
    }
done

# System files restored as-is (subject to the hardware rules).
ETC_APPLY=(
    /etc/NetworkManager/conf.d/80-wifi-powersave.conf
    /etc/NetworkManager/conf.d/90-cloudflare-dnscrypt.conf
    /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    /etc/sysctl.d/50-kde-inotify-survey-max_user_instances.conf
    /etc/sysctl.d/50-kde-inotify-survey-max_user_watches.conf
    /etc/sysctl.d/99-inotify.conf
    /etc/sysctl.d/99-zram-vm.conf
    /etc/systemd/zram-generator.conf
    /etc/systemd/system/irqbalance.service.d/10-proc-irq-writable.conf
    /etc/systemd/system/laptop-auto-battery-life.service
    /etc/udev/rules.d/85-laptop-auto-battery-life.rules
    /etc/laptop-battery-life.conf
    /etc/docker/daemon.json
    /etc/cron.d/update-stevenblack-hosts
    /etc/locale.conf
    /etc/locale.gen
    /etc/vconsole.conf
    /usr/local/sbin/laptop-auto-battery-life
    /usr/local/sbin/update-stevenblack-hosts
)

# Boot, kernel-module, repository, and access-control files: recorded for
# review only, because a copy on different hardware can stop a machine booting.
ETC_REFERENCE=(
    /etc/default/grub
    /etc/mkinitcpio.conf
    /etc/mkinitcpio.d/linux-zen.preset
    /etc/modprobe.d/nvidia-drm.conf
    /etc/modules-load.d/graphics-typec.conf
    /etc/modules-load.d/nvidia.conf
    /etc/modules-load.d/typec.conf
    /etc/conf.d/lm_sensors
    /etc/pacman.conf
    /etc/firejail/firejail.users
)

# KDE and desktop settings. Panels are generated by apply-panels.sh, and
# monitor layouts are hardware-specific, so neither is recorded here.
HOME_CONFIG=(
    .config/kdeglobals
    .config/kwinrc
    .config/kwinrulesrc
    .config/kglobalshortcutsrc
    .config/plasmanotifyrc
    .config/plasma-localerc
    .config/powerdevilrc
    .config/powermanagementprofilesrc
    .config/ksmserverrc
    .config/kscreenlockerrc
    .config/baloofilerc
    .config/dolphinrc
    .config/konsolerc
    .config/spectaclerc
    .config/gwenviewrc
    .config/okularrc
    .config/kiorc
    .config/klassy/klassyrc
    .config/mimeapps.list
    .config/gtk-3.0/settings.ini
    .config/gtk-4.0/settings.ini
    .config/xsettingsd/xsettingsd.conf
)

rm -rf -- "${OUT:?}/packages" "${OUT:?}/units" "${OUT:?}/etc" \
    "${OUT:?}/etc-reference" "${OUT:?}/home"
mkdir -p -- "$OUT/packages" "$OUT/units"

sorted() { LC_ALL=C sort -u; }

# Packages: explicit installs from the sync repositories and from the AUR.
pacman -Qqen | sorted >"$OUT/packages/pacman.txt"
pacman -Qqem | sorted >"$OUT/packages/aur.txt"

pnpm_root="${XDG_DATA_HOME:-$HOME/.local/share}/pnpm/global"
: >"$OUT/packages/pnpm-global.txt"
if [[ -d $pnpm_root ]]; then
    python3 - "$pnpm_root" >"$OUT/packages/pnpm-global.txt" <<'PY'
import json, pathlib, sys
names = set()
root = pathlib.Path(sys.argv[1])
# pnpm 11 keeps one isolated project per global install below global/v11/.
for manifest in list(root.glob("*/package.json")) + list(root.glob("*/*/package.json")):
    for name in json.loads(manifest.read_text()).get("dependencies", {}):
        installed = manifest.parent / "node_modules" / name / "package.json"
        if installed.is_file():
            names.add(f"{name}@{json.loads(installed.read_text())['version']}")
print("\n".join(sorted(names)))
PY
fi

python3 - "$HOME/.local/lib/node_modules" >"$OUT/packages/npm-global.txt" <<'PY'
import json, pathlib, sys
root = pathlib.Path(sys.argv[1])
found = []
for manifest in list(root.glob("*/package.json")) + list(root.glob("@*/*/package.json")):
    data = json.loads(manifest.read_text())
    found.append(f"{data['name']}@{data['version']}")
print("\n".join(sorted(found)))
PY

: >"$OUT/packages/uv-tools.txt"
if command -v uv >/dev/null 2>&1; then
    uv tool list 2>/dev/null | awk '/^[^- ]/ {sub(/^v/, "", $2); print $1 "==" $2}' \
        | sorted >"$OUT/packages/uv-tools.txt"
fi
: >"$OUT/packages/pipx.txt"
if command -v pipx >/dev/null 2>&1; then
    pipx list --short 2>/dev/null | awk '{print $1 "==" $2}' | sorted >"$OUT/packages/pipx.txt"
fi
: >"$OUT/packages/flatpak.txt"
if command -v flatpak >/dev/null 2>&1; then
    flatpak list --app --columns=application 2>/dev/null | sorted >"$OUT/packages/flatpak.txt"
fi

# Services: system units enabled beyond the vendor preset, masked units, and
# every enabled user unit.
systemctl list-unit-files --state=enabled --no-legend --no-pager \
    | awk '$3 != "enabled" {print $1}' | sorted >"$OUT/units/system-enabled.txt"
systemctl list-unit-files --state=masked --no-legend --no-pager \
    | awk '{print $1}' | sorted >"$OUT/units/system-masked.txt"
systemctl --user list-unit-files --state=enabled --no-legend --no-pager \
    | awk '{print $1}' | sorted >"$OUT/units/user-enabled.txt"
systemctl --user list-unit-files --state=masked --no-legend --no-pager \
    | awk '{print $1}' | sorted >"$OUT/units/user-masked.txt"

# Supplementary groups that grant device or service access.
id -nG | tr ' ' '\n' | grep -vxF -e "$HOST_USER" | sorted >"$OUT/units/groups.txt"

copy_tree() {
    local destination=$1 path
    shift
    for path in "$@"; do
        if [[ ! -r $path ]]; then
            printf 'capture-machine: skipped unreadable or missing %s\n' "$path" >&2
            continue
        fi
        mkdir -p -- "$destination$(dirname -- "$path")"
        python3 - "$path" "$destination$path" "$HOST_HOME" "$HOST_USER" <<'PY'
import pathlib, re, sys
source, target, home, user = sys.argv[1:5]
text = pathlib.Path(source).read_text()
text = text.replace(home, "__HOME__")
text = re.sub(rf"(?m)^{re.escape(user)}$", "__USER__", text)
pathlib.Path(target).write_text(text)
PY
        chmod --reference="$path" -- "$destination$path"
    done
}

copy_tree "$OUT/etc" "${ETC_APPLY[@]}"
copy_tree "$OUT/etc-reference" "${ETC_REFERENCE[@]}"

# KDE settings without window geometry, recent files, or other session state.
for relative in "${HOME_CONFIG[@]}"; do
    [[ -r $HOME/$relative ]] || continue
    mkdir -p -- "$OUT/home/$(dirname -- "$relative")"
    python3 - "$HOME/$relative" "$OUT/home/$relative" "$HOST_HOME" <<'PY'
import pathlib, re, sys
source, target, home = sys.argv[1:4]
volatile_group = re.compile(
    r"^\[(\$Version|MainWindow|KFileDialog Settings|Recent|.*Recent .*|.*History.*|"
    r"PlasmaViews|Tiling|FileDialogSize|.*saved at previous logout)\b",
    re.IGNORECASE,
)
volatile_key = re.compile(
    r"^(State|Window-Maximized|Height |Width |.*screens?: |.*Recent.*|"
    r"Last.*(Url|Location)|ViewPropsTimestamp|ToolBarsMovable|Splitter.*|Geometry|.*Geometry.*|"
    r"MenuBar|StatusBar|ShowPanel|.*XPosition|.*YPosition)",
    re.IGNORECASE,
)
lines, skipping = [], False
for line in pathlib.Path(source).read_text().splitlines():
    if line.startswith("["):
        skipping = bool(volatile_group.match(line))
    if skipping or volatile_key.match(line):
        continue
    lines.append(line.replace(home, "__HOME__"))
# Drop groups left without keys after filtering.
groups, current = [], None
for line in lines:
    if line.startswith("["):
        current = [line, []]
        groups.append(current)
    elif current is None:
        groups.append([None, [line]])
    elif line.strip():
        current[1].append(line)
blocks = ["\n".join(([header] if header else []) + body) for header, body in groups if body]
if blocks:
    pathlib.Path(target).write_text("\n\n".join(blocks) + "\n")
PY
done

printf 'Captured %s pacman, %s AUR, and %s user-tool entries into %s\n' \
    "$(wc -l <"$OUT/packages/pacman.txt")" "$(wc -l <"$OUT/packages/aur.txt")" \
    "$(cat "$OUT"/packages/{pnpm-global,npm-global,uv-tools,pipx,flatpak}.txt | grep -c . || true)" \
    "${OUT#"$ROOT"/}"
printf 'Review with: git diff -- %s\n' "${OUT#"$ROOT"/}"
